### PR TITLE
Bump to version 3.0.0

### PR DESCRIPTION
**Pull request by Vedingrot**
Due to API changes, version should be updated to next major.

### CODE REVIEW

**Comment by Vedingrot** [comment]
Can you also set tag in repo to create a new tarball, Thanks in advance

**Comment by rinigus** [comment]
This is too early as corresponding MapLibre GL Qt is not released yet. As such, QML plugin API stayed the same, but we can change major version as well when the time comes. But before QML plugin release, I would prefer to have a fixed released version of MapLibre GL Qt. Note that as soon as MapLibre GL Qt release is tagged, I would have to update and test QML plugin against it.

Issue regarding MapLibre GL Qt release: https://github.com/maplibre/maplibre-native-qt/issues/92

**Comment by Vedingrot** [comment]
Hi, MapLibre GL Qt v3.0.0 has been released!

**Comment by rinigus** [comment]
yes, we were following the same issue :) .

I would have to finish few tasks I am working on and then start testing with the new maplibre. have you checked if this PR works for you with 3.0.0?

**Comment by rinigus** [comment]
Merging as together with the other merged PR it should work

**Pull request merged**
